### ISSUE TITLE
Is this going to be open sourced?

### ISSUE THREAD

**Issue by ImranR98** [ProtonMail/inbox-desktop#13]

**Comment by mietinen** [comment]
Well, according to the license they are legally obligated to provide you with the source code if you request it.
I'm not sure they are obligated to host the source code online, as long as its "available" in some way or another.

**Comment by flavienbonvin** [comment]
Hello, the source are now available on the latest release. You can find them here: https://github.com/ProtonMail/inbox-desktop/releases/tag/v1.0.1
