### ISSUE TITLE
Closed window cannot be reopened

### ISSUE THREAD

**Issue by datashaman** [ProtonMail/inbox-desktop#14]
I am on MacOS Sonoma 14.2.1 (23C71).

To replicate:
* Launch ProtonMail.
* Press CMD-W to close the window.

ProtonMail is left running without any way of reopening the window.

When I use the Refresh menu item, the following error appears.

![CleanShot 2024-03-17 at 11 22 39@2x](https://github.com/ProtonMail/inbox-desktop/assets/59514/06b11c59-9e77-45a2-9d43-838eae936990)

The only way to get it back to a functioning state is to restart it.

The refresh functionality works as expected if I have not closed the window.

**Comment by jimmy213** [comment]
Same here in macOS Sonoma 14.4 (23E214). This behaviour started since ver. 1.0.0

**Comment by jordanmontt** [comment]
I confirm that I have the same issue in OSX Sonoma 14.3.1

**Comment by flavienbonvin** [comment]
Thanks for the report, this will be fixed in update 1.0.1 that is expected very soon

**Comment by jordanmontt** [comment]
Thanks! With the new downloaded version, 1.0.1, this issue is solved for my machine (OSX Sonoma 14.3.1)

**Comment by jimmy213** [comment]
I can also confirm that with v.1.0.1 the issue has resolved. Thank you.

**Comment by flavienbonvin** [comment]
You're welcome!
