### ISSUE TITLE
Calendar Error Since 1.0.1 update

### ISSUE THREAD

**Issue by ccampbell9** [ProtonMail/inbox-desktop#16]
Hello, 

Since the update to 1.0.1, switching to the calendar view now fails with the following error:

`Error: App version outdated` 

OS: Linux, Fedora 39
Release version: 1.0.1
Package type: rpm

**Comment by qrkourier** [comment]
Same error after installing 1.0.1 DEB downloaded from https://proton.me/download/mail/linux/ProtonMail-desktop-beta.deb.

![image](https://github.com/ProtonMail/inbox-desktop/assets/1434400/37687fd1-589b-432d-bd4c-93a1889e5668)

```bash
 ❯ sha256sum /tmp/ProtonMail-desktop-beta.deb 
dc5466d36130f46b8631714093048bf856de2f2688d529a90d4dc0e5e261e935  /tmp/ProtonMail-desktop-beta.deb

 ❯  cat /etc/lsb-release /etc/os-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by flavienbonvin** [comment]
Hi, sorry for the inconvenience, the calendar client was updated, and you should now be able to access calendar. Please let me know if you're still facing issue.
