### ISSUE TITLE
git tracking

### ISSUE THREAD

**Issue by midirhee12** [ProtonMail/inbox-desktop#37]
It's odd that the sources are only available via `.zip`. The only thing available in the repository is the `README` and `LICENSE` files. The sources should be version tracked via git (like every other project) as well instead of some release tag with a `.zip` file.

Why are we preventing contributions? Why are we afraid of version tracked development? What's to be afraid of?

**Comment by flavienbonvin** [comment]
The objective is to integrate the desktop application code into the web clients monorepo (https://github.com/ProtonMail/WebClients). Upon successful integration, the entire Git history will be accessible within the monorepo.
