### ISSUE TITLE
Create separate Calendar launcher

### ISSUE THREAD

**Issue by traktuner** [ProtonMail/inbox-desktop#4]
Hello,
It would be great to have a separate Calendar launcher.
I use both apps most of the time, but I'd like to have both in my macOS dock, to have the option to open the apps separately without first opening mail, clicking the app selector and chosing calendar.
Thank you!

**Comment by flavienbonvin** [comment]
Hello,
thanks for the feedback, this is something that was reported by several users. We added your report to our board, and we will take a look at our option to make it work best!

**Comment by traktuner** [comment]
Thanks very much!
Also to add - it would be good if the window sizes get treated separately. When Mail is fullscreen, Calendar also opens in fullscreen - I always have Calendar at a very small size (and Mail in fullscreen) and need to adjust it every time.
